apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "service" }} 
spec:
  selector:
    app: {{ printf "%s-%s" .Release.Name "frontend" }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: 80
